## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [3]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Albany,US,42.6001,-73.9662,50.72,82,100,3.74,overcast clouds
1,1,Bela,IN,25.9333,81.9833,78.96,82,6,5.46,clear sky
2,2,Port Blair,IN,11.6667,92.7500,81.14,83,100,6.42,overcast clouds
3,3,Vardo,NO,70.3705,31.1107,39.60,75,90,13.71,overcast clouds
4,4,Atuona,PF,-9.8000,-139.0333,78.69,72,11,10.65,few clouds

In [16]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 90

In [17]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Bela,IN,25.9333,81.9833,78.96,82,6,5.46,clear sky
2,2,Port Blair,IN,11.6667,92.7500,81.14,83,100,6.42,overcast clouds
4,4,Atuona,PF,-9.8000,-139.0333,78.69,72,11,10.65,few clouds
6,6,Marakkanam,IN,12.2000,79.9500,87.22,67,90,14.52,overcast clouds
13,13,Ormara,PK,25.2088,64.6357,84.20,86,2,16.80,clear sky
18,18,Port-Gentil,GA,-0.7193,8.7815,79.23,86,100,12.86,light rain
19,19,Meulaboh,ID,4.1363,96.1285,77.40,87,89,2.98,overcast clouds
20,20,Hilo,US,19.7297,-155.0900,77.61,78,20,0.00,light rain
26,26,Saint-Philippe,RE,-21.3585,55.7679,71.15,78,37,5.82,scattered clouds
31,31,Aquin,HT,18.2833,-73.4000,84.15,64,8,8.93,clear sky

In [18]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

Unnamed: 0             277
City                   277
Country                277
Lat                    277
Lng                    277
Max Temp               277
Humidity               277
Cloudiness             277
Wind Speed             277
Current Description    277
dtype: int64

In [19]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
preferred_cities_df.dropna()

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Bela,IN,25.9333,81.9833,78.96,82,6,5.46,clear sky
2,2,Port Blair,IN,11.6667,92.7500,81.14,83,100,6.42,overcast clouds
4,4,Atuona,PF,-9.8000,-139.0333,78.69,72,11,10.65,few clouds
6,6,Marakkanam,IN,12.2000,79.9500,87.22,67,90,14.52,overcast clouds
13,13,Ormara,PK,25.2088,64.6357,84.20,86,2,16.80,clear sky
...,...,...,...,...,...,...,...,...,...,...
675,675,Hvittingfoss,NO,59.4833,10.0167,75.45,42,4,1.01,clear sky
680,680,Catuday,PH,16.2923,119.8062,83.25,76,81,8.61,broken clouds
682,682,Denpasar,ID,-8.6500,115.2167,78.46,94,20,6.33,few clouds
683,683,Puerto Ayacucho,VE,5.6639,-67.6236,83.55,76,91,1.19,overcast clouds
684,684,Kharar,IN,30.7444,76.6478,84.56,50,12,9.19,few clouds

In [21]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Bela,IN,78.96,clear sky,25.9333,81.9833,
2,Port Blair,IN,81.14,overcast clouds,11.6667,92.7500,
4,Atuona,PF,78.69,few clouds,-9.8000,-139.0333,
6,Marakkanam,IN,87.22,overcast clouds,12.2000,79.9500,
13,Ormara,PK,84.20,clear sky,25.2088,64.6357,
18,Port-Gentil,GA,79.23,light rain,-0.7193,8.7815,
19,Meulaboh,ID,77.40,overcast clouds,4.1363,96.1285,
20,Hilo,US,77.61,light rain,19.7297,-155.0900,
26,Saint-Philippe,RE,71.15,scattered clouds,-21.3585,55.7679,
31,Aquin,HT,84.15,clear sky,18.2833,-73.4000,

In [23]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [35]:
hotel_df.tail(50)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
555,Tshikapa,CD,79.72,broken clouds,-6.4167,20.8000,Hôtel Tshia-Muntu de Tshikapa
558,Russell,US,81.68,scattered clouds,32.3502,-85.1999,Macs
559,Viransehir,TR,75.83,broken clouds,37.2353,39.7631,Viranşehir Öğretmenevi
560,Ixtapa,MX,83.43,clear sky,20.7000,-105.2000,Hotel Plaza Providencia
565,Bontang,ID,78.30,scattered clouds,0.1333,117.5000,KOPKAR Hotel Bintang Sintuk
569,Belmonte,BR,81.10,overcast clouds,-15.8631,-38.8828,Pousada Monte Carmelo O Pão
570,Conde,BR,81.86,scattered clouds,-7.2597,-34.9075,Pousada Beija Flor
575,San Ramon,US,70.59,few clouds,37.7799,-121.9780,San Ramon Marriott
579,Amol,IR,78.26,clear sky,36.4696,52.3507,Shahr Hotel
582,Dillon,US,88.20,overcast clouds,34.4166,-79.3712,Dillon Express Inn
583,Isangel,VU,70.25,broken clouds,-19.5500,169.2667,Tanna Lodge
586,Noumea,NC,71.01,overcast clouds,-22.2763,166.4572,Hôtel Le Lagon
588,Benguela,AO,76.68,scattered clouds,-12.5763,13.4055,Hotel Praia Morena
589,Havelock,US,88.05,broken clouds,34.8791,-76.9013,Sherwood Motel
591,Alcantara,BR,88.00,broken clouds,-2.4089,-44.4147,Pousada da Josefa
593,Harper,LR,82.47,broken clouds,4.3750,-7.7169,Screensaver
594,Gafargaon,BD,85.98,few clouds,24.4333,90.5667,গফরগাঁও ধামাইল ঢালীবাড়ী
595,Monrovia,LR,83.97,light rain,6.3005,-10.7969,Sunset Inn
598,Hurricane,US,87.71,broken clouds,37.1753,-113.2899,Super 8 by Wyndham Hurricane Zion National Park
601,Abu Samrah,SY,71.76,clear sky,35.3029,37.1841,
602,Tagab,AF,80.51,broken clouds,34.8550,69.6492,
605,Saint-Pierre,RE,71.24,clear sky,-21.3393,55.4781,Lindsey Hôtel
608,Kiunga,PG,71.56,overcast clouds,-6.1219,141.2906,Airport Lodge Kiunga
609,Puerto Palomas,MX,88.93,clear sky,31.7667,-107.6167,Hotel San Carlos
616,Kavaratti,IN,83.39,broken clouds,10.5669,72.6420,Hotels in Lakshadweep Islands
617,Pueblo,US,81.45,clear sky,38.2545,-104.6091,Courtyard by Marriott Pueblo Downtown
618,Damara,CF,81.19,broken clouds,4.9608,18.7035,
620,Indramayu,ID,78.58,overcast clouds,-6.3264,108.3200,Grand Trisula Hotel
623,Gunjur,GM,80.67,clear sky,13.2019,-16.7339,Kuba Lodge
627,Dakar,SN,81.48,clear sky,14.6937,-17.4441,Redface Studios Meublés
632,Kampot,KH,78.85,few clouds,10.6167,104.1833,Two Moons Hotel
635,Pio Xii,BR,87.42,scattered clouds,-3.8325,-45.1525,BACURI DOS QUARESMAS
640,Portland,US,71.10,few clouds,45.5234,-122.6762,Embassy Suites by Hilton Portland Downtown
645,Xuddur,SO,77.18,overcast clouds,4.1213,43.8894,Banjanay Hotel
647,Oistins,BB,86.09,scattered clouds,13.0667,-59.5333,Butterfly Beach Hotel
656,Cap Malheureux,MU,75.69,light rain,-19.9842,57.6142,Pereybere Hotel & Spa
657,Tallahassee,US,87.67,scattered clouds,30.4383,-84.2807,Four Points by Sheraton Tallahassee Downtown
658,Aksu,CN,78.76,scattered clouds,41.1231,80.2644,Pudong Holiday Hotel
660,Samarskoye,RU,74.21,overcast clouds,46.9336,39.6814,Хостел ТЕСЛА
662,Adjumani,UG,73.60,overcast clouds,3.3779,31.7909,Hotel Zawadi
663,Kinkala,CG,78.96,scattered clouds,-4.3614,14.7644,Hotel la Pepeche Kinkala
665,Trogir,HR,71.65,clear sky,43.5125,16.2517,Hotel Medena
667,Bonthe,SL,84.27,broken clouds,7.5264,-12.5050,Bonthe Holiday Village
669,San Vicente,AR,70.39,overcast clouds,-26.6167,-54.1333,Complejo Turístico Farelluk
672,Barahona,DO,87.62,few clouds,18.2085,-71.1008,Hotel Caribe
675,Hvittingfoss,NO,75.45,clear sky,59.4833,10.0167,Reinemoen
680,Catuday,PH,83.25,broken clouds,16.2923,119.8062,GResort
682,Denpasar,ID,78.46,few clouds,-8.6500,115.2167,ASTON Denpasar Hotel & Convention Center
683,Puerto Ayacucho,VE,83.55,overcast clouds,5.6639,-67.6236,Posada Turistica Manapiare
684,Kharar,IN,84.56,few clouds,30.7444,76.6478,OYO 19817 Hotel Sartaj

In [38]:
import numpy as np
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.replace(r'^\s*$', np.nan, regex=True)
clean_hotel_df.dropna()
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Bela,IN,78.96,clear sky,25.9333,81.9833,Raj Bhawan
2,Port Blair,IN,81.14,overcast clouds,11.6667,92.7500,"Welcomhotel By ITC Hotels, Bay Island, Port Blair"
4,Atuona,PF,78.69,few clouds,-9.8000,-139.0333,Villa Enata
6,Marakkanam,IN,87.22,overcast clouds,12.2000,79.9500,OYO 73765 Ocean Breeze Guest House
13,Ormara,PK,84.20,clear sky,25.2088,64.6357,Crystal Beach and Camping Resort Ormara
18,Port-Gentil,GA,79.23,light rain,-0.7193,8.7815,Fengshui Residence
19,Meulaboh,ID,77.40,overcast clouds,4.1363,96.1285,Kost Pria
20,Hilo,US,77.61,light rain,19.7297,-155.0900,Hilo Hawaiian Hotel
26,Saint-Philippe,RE,71.15,scattered clouds,-21.3585,55.7679,"Chambres d'hôte ""La Trinité"""
31,Aquin,HT,84.15,clear sky,18.2833,-73.4000,Asheev Beach

In [40]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [52]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [53]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))